version: "3"

services:
  wordpress_app:
    image: wordpress:latest
    ports: 
      - 8000:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress_user
      - WORDPRESS_DB_PASSWORD=UkgwiDot089056
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=PaodT560543
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress_user
      - MYSQL_PASSWORD=UkgwiDot089056
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: